from pathlib import Path
import json
import markdown

# ==========================================================
# DOCS_OS Builder v0.3.1-alpha
# Supply Chain Radar Documentation Generator
# ==========================================================

# Root directory of DOCS_OS
ROOT = Path(__file__).parent

# Important folders
CONFIG_DIR = ROOT / "04_GENERATORS" / "config"
THEME_DIR = ROOT / "01_THEMES" / "apple_dark"
OUTPUT_DIR = ROOT / "05_EXPORTS" / "html"

# Create output folder if it doesn't exist
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------
# Load Configuration
# ----------------------------------------------------------

with open(CONFIG_DIR / "config.json", "r", encoding="utf-8") as f:
    CONFIG = json.load(f)

with open(CONFIG_DIR / "theme.json", "r", encoding="utf-8") as f:
    THEME = json.load(f)

# ----------------------------------------------------------
# Load Theme CSS
# ----------------------------------------------------------

THEME_CSS = (THEME_DIR / "theme.css").read_text(encoding="utf-8")


# ----------------------------------------------------------
# Markdown → HTML Builder
# ----------------------------------------------------------

def build_document(markdown_file: Path):

    markdown_text = markdown_file.read_text(encoding="utf-8")

    body = markdown.markdown(
        markdown_text,
        extensions=[
            "tables",
            "fenced_code",
            "toc"
        ]
    )

    html = f"""
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>{CONFIG["project_name"]}</title>

<style>
{THEME_CSS}
</style>

</head>

<body>

<div class="page">

    <div class="hero">

        <span class="badge success">{CONFIG["docs_version"]}</span>

        <h1>{CONFIG["project_name"]}</h1>

        <p>AI-powered Supply Chain Intelligence Platform.</p>

        <p>
            <strong>Author</strong> · {CONFIG["author"]}
        </p>

    </div>

    {body}

    <div class="footer">

        Generated by DOCS_OS · Version {CONFIG["docs_version"]}

    </div>

</div>

</body>

</html>
"""

    output_file = OUTPUT_DIR / f"{markdown_file.stem}.html"

    output_file.write_text(html, encoding="utf-8")

    print(f"✅ HTML Generated → {output_file}")


# ----------------------------------------------------------
# Build Entry
# ----------------------------------------------------------

def build():

    sample_doc = ROOT / "06_EXAMPLES" / "PROJECT_SAMPLE.md"

    if not sample_doc.exists():
        print("❌ PROJECT_SAMPLE.md not found.")
        return

    build_document(sample_doc)


if __name__ == "__main__":
    build()