import markdown
from markdown.extensions import tables, fenced_code, sane_lists, nl2br, attr_list
from markdown.extensions.toc import TocExtension


def parse_markdown(markdown_text: str) -> str:
    """
    DOCS_OS Markdown Parser v1.0

    Converts Markdown into clean HTML while preserving fenced code blocks
    for the CodeBlock Builder and callout syntax for the Callout Builder.
    """

    md = markdown.Markdown(
        extensions=[
            tables.TableExtension(),
            fenced_code.FencedCodeExtension(),
            sane_lists.SaneListExtension(),
            nl2br.Nl2BrExtension(),
            attr_list.AttrListExtension(),

            TocExtension(
                permalink=False,
                baselevel=1,
                marker=""
            )
        ],
        output_format="html5"
    )

    html = md.convert(markdown_text)

    # Remove empty paragraphs generated by markdown.
    html = html.replace("<p></p>", "")

    # Better horizontal rules.
    html = html.replace("<hr />", "<hr>")

    return html