from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

CSS = ROOT / "01_THEMES" / "apple_dark" / "theme.css"


def build_html(metadata, content):

    css = CSS.read_text(encoding="utf-8")

    return f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>{metadata["Title"]}</title>

<style>

{css}

</style>

</head>

<body>

<div class="page">

<header class="hero-card">

<span class="version-pill">v{metadata["Version"]}</span>

<h1>{metadata["Title"]}</h1>

<p class="hero-subtitle">
Official Supply Chain Radar Documentation
</p>

<p class="hero-author">
Author • {metadata["Owner"]}
</p>

</header>

<section>

<h2>Document Metadata</h2>

<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>Document ID</td><td>{metadata["Document ID"]}</td></tr>
<tr><td>Department</td><td>{metadata["Department"]}</td></tr>
<tr><td>Version</td><td>{metadata["Version"]}</td></tr>
<tr><td>Status</td><td>{metadata["Status"]}</td></tr>
<tr><td>Owner</td><td>{metadata["Owner"]}</td></tr>
<tr><td>Documentation Engine</td><td>{metadata["Documentation Engine"]}</td></tr>
<tr><td>Last Updated</td><td>{metadata["Last Updated"]}</td></tr>
</table>

</section>

<hr>

<main>

{content}

</main>

<footer class="footer">

PROJECT_{metadata["Document ID"][-3:]} • Version {metadata["Version"]}

<br><br>

Generated by DOCS_OS

</footer>

</div>

</body>

</html>"""