from pathlib import Path

from src.theme_engine.theme_engine import load_theme
from src.builder.sidebar_builder import build_sidebar
from src.builder.callout_builder import replace_callouts
from src.builder.codeblock_builder import replace_codeblocks

ROOT = Path(__file__).resolve().parents[2]

# ==========================================================
# Load Component Assets
# ==========================================================

SIDEBAR_CSS = (
    ROOT / "02_COMPONENTS/sidebar/sidebar.css"
).read_text(encoding="utf-8")

SIDEBAR_JS = (
    ROOT / "02_COMPONENTS/sidebar/sidebar.js"
).read_text(encoding="utf-8")

CALLOUT_CSS = (
    ROOT / "02_COMPONENTS/callouts/callout.css"
).read_text(encoding="utf-8")

CODEBLOCK_CSS = (
    ROOT / "02_COMPONENTS/codeblocks/codeblock.css"
).read_text(encoding="utf-8")

CODEBLOCK_JS = (
    ROOT / "02_COMPONENTS/codeblocks/codeblock.js"
).read_text(encoding="utf-8")


# ==========================================================
# HTML Builder
# ==========================================================

def build_html(metadata, html_content):
    """
    DOCS_OS HTML Builder
    Apple Charcoal v0.4
    """

    # Load theme
    theme = load_theme("apple_dark")

    # Sidebar
    sidebar = build_sidebar(metadata["document_id"])

    # Markdown components
    html_content = replace_callouts(html_content)
    html_content = replace_codeblocks(html_content)

    return f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>{metadata["title"]}</title>

<style>

{theme}

{SIDEBAR_CSS}

{CALLOUT_CSS}

{CODEBLOCK_CSS}

</style>

</head>

<body>

<button id="menuButton">☰</button>

{sidebar}

<div class="overlay" id="overlay"></div>

<div class="page">

    <!-- ====================================================== -->
    <!-- HERO -->
    <!-- ====================================================== -->

    <section class="hero">

        <small>DOCS_OS • v{metadata["version"]}</small>

        <h1>{metadata["title"]}</h1>

        <p>
            Official documentation standard for Supply Chain Radar.
        </p>

    </section>

    <!-- ====================================================== -->
    <!-- METADATA -->
    <!-- ====================================================== -->

    <section class="metadata-card">

        <div>
            <strong>Status</strong>
            <span>{metadata["status"]}</span>
        </div>

        <div>
            <strong>Owner</strong>
            <span>{metadata["owner"]}</span>
        </div>

        <div>
            <strong>Department</strong>
            <span>{metadata["department"]}</span>
        </div>

        <div>
            <strong>Generator</strong>
            <span>{metadata["generator"]}</span>
        </div>

    </section>

    <!-- ====================================================== -->
    <!-- CONTENT -->
    <!-- ====================================================== -->

    <main class="document-content">

{html_content}

    </main>

    <!-- ====================================================== -->
    <!-- FOOTER -->
    <!-- ====================================================== -->

    <footer class="footer">

        PROJECT {metadata["document_id"]} • Version {metadata["version"]}

        <br><br>

        Generated by DOCS_OS • {metadata["generator"]}

    </footer>

</div>

<script>

{SIDEBAR_JS}

{CODEBLOCK_JS}

</script>

</body>

</html>
"""