from pathlib import Path

from src.theme_engine.theme_engine import load_theme
from src.builder.sidebar_builder import build_sidebar
from src.builder.callout_builder import replace_callouts

ROOT = Path(__file__).resolve().parents[2]

# Components
SIDEBAR_CSS = (
    ROOT / "02_COMPONENTS/sidebar/sidebar.css"
).read_text(encoding="utf-8")

SIDEBAR_JS = (
    ROOT / "02_COMPONENTS/sidebar/sidebar.js"
).read_text(encoding="utf-8")

# ✅ Correct location (only one callout CSS file)
CALLOUT_CSS = (
    ROOT / "02_COMPONENTS/callouts/callout.css"
).read_text(encoding="utf-8")


def build_html(metadata, html_content):
    """Build a DOCS_OS HTML document."""

    theme = load_theme("apple_dark")
    sidebar = build_sidebar(metadata["document_id"])

    # Convert markdown callouts into premium HTML callout cards
    html_content = replace_callouts(html_content)

    return f"""<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>{metadata["title"]}</title>

<style>

{theme}

{SIDEBAR_CSS}

{CALLOUT_CSS}

</style>

</head>

<body>

<button id="menuButton">☰</button>

{sidebar}

<div class="overlay" id="overlay"></div>

<div class="page">
<div class="container">

<div class="hero">

<div class="version-badge">
{metadata["version"]}
</div>

<h1>{metadata["title"]}</h1>

<p>Official Supply Chain Radar Documentation</p>

</div>

<div class="metadata-card">

<div><strong>Status</strong> {metadata["status"]}</div>

<div><strong>Owner</strong> {metadata["owner"]}</div>

<div><strong>Department</strong> {metadata["department"]}</div>

<div><strong>Generator</strong> {metadata["generator"]}</div>

</div>

{html_content}

<footer>

PROJECT {metadata["document_id"]} • Version {metadata["version"]}

<br><br>

Generated by DOCS_OS

</footer>

</div>
</div>

<script>

{SIDEBAR_JS}

</script>

</body>
</html>
"""